In [2]:
from RUN_ALL_LIB import *
import warnings
import gc
import torch
#warnings.filterwarnings("ignore", category=DeprecationWarning)
import os
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
import logging
#logging.getLogger("transformers").setLevel(logging.ERROR)
import warnings
#warnings.filterwarnings("ignore", message="Setting `pad_token_id` to `eos_token_id`")

In [ ]:
# ==================== FFT QA TEST 1 ====================

run_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    token=os.getenv("HF_TOKEN"),
    max_new_tokens=1300,
    num_epoch=3,
    test_status=False,
    learn_len=512,
    batch_size=1,
    device_batch_size=1,
    padding=False,
    data_collator_type="new",
)

===== FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct =====
[transformers] `torch_dtype` is deprecated! Use `dtype` instead!
Loading widget...
Loading widget...
Loading widget...
 [177/177 06:17, Epoch 3/3]
Epoch	Training Loss	Validation Loss
1	0.261471	0.217478
2	0.134586	0.132731
3	0.106895	0.126220
Loading widget...
Loading widget...
Loading widget...

In [2]:
# ==================== FFT QA TEST 2 ====================

run_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    token=os.getenv("HF_TOKEN"),
    max_new_tokens=1300,
    num_epoch=3,
    test_status=False,
    learn_len=512,
    batch_size=1,
    device_batch_size=1,
    padding=False,
    data_collator_type="old",
    make_test = False
)

===== FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/940 [00:00<?, ? examples/s]

Map:   0%|          | 0/105 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[after Full Finetune] allocated=18400.9MB reserved=27780.0MB max_alloc=26787.5MB
[after Full Finetune cleanup] allocated=18400.9MB reserved=18560.0MB max_alloc=26787.5MB

In [2]:
# ==================== FFT QA TEST 3 ====================

run_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    token=os.getenv("HF_TOKEN"),
    max_new_tokens=1300,
    num_epoch=5,
    test_status=False,
    learn_len=512,
    batch_size=1,
    device_batch_size=1,
    padding=False,
    data_collator_type="new",
    make_test = False
)

===== FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/940 [00:00<?, ? examples/s]

Map:   0%|          | 0/105 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[after Full Finetune] allocated=18400.9MB reserved=27780.0MB max_alloc=26788.4MB
[after Full Finetune cleanup] allocated=18400.9MB reserved=18560.0MB max_alloc=26788.4MB

In [2]:
# ==================== FFT QA TEST 4 ====================

run_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    token=os.getenv("HF_TOKEN"),
    max_new_tokens=1300,
    num_epoch=3,
    test_status=False,
    learn_len=1024,
    batch_size=1,
    device_batch_size=1,
    padding=False,
    data_collator_type="new",
    make_test = False
)

===== FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/940 [00:00<?, ? examples/s]

Map:   0%|          | 0/105 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[after Full Finetune] allocated=18400.9MB reserved=28316.0MB max_alloc=26792.6MB
[after Full Finetune cleanup] allocated=18400.9MB reserved=20190.0MB max_alloc=26792.6MB

In [2]:
# ==================== FFT QA TEST 5 ====================

run_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    token=os.getenv("HF_TOKEN"),
    max_new_tokens=1300,
    num_epoch=5,
    test_status=False,
    learn_len=1024,
    batch_size=1,
    device_batch_size=1,
    padding=False,
    data_collator_type="new",
    make_test = False
)

===== FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/940 [00:00<?, ? examples/s]

Map:   0%|          | 0/105 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [2]:
# ==================== FFT UNSUP TEST 1 ====================

run_unsupervised_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    corpus_path="dataset.txt",
    token=os.getenv("HF_TOKEN"),
    num_epoch=3,
    batch_size=1,
    grad_accum_steps=8,
    lr=1e-5,
    max_seq_length=512,
    chunk_size_sym=1500,
    overlap_sym=150,
    val_split=0.05,
    optim="adamw_torch_fused",
    test_status=False,
    make_test = False,
)

===== UNSUPERVISED FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct on dataset.txt =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/1355 [00:00<?, ? examples/s]

Map:   0%|          | 0/72 [00:00<?, ? examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Loss: 2.0737
Validation Perplexity: 7.95

In [2]:
# ==================== FFT UNSUP TEST 2 ====================

run_unsupervised_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    corpus_path="dataset.txt",
    token=os.getenv("HF_TOKEN"),
    num_epoch=3,
    batch_size=1,
    grad_accum_steps=8,
    lr=5e-6,
    max_seq_length=512,
    chunk_size_sym=1500,
    overlap_sym=150,
    val_split=0.05,
    optim="adamw_torch_fused",
    test_status=False,
    make_test = False
)

===== UNSUPERVISED FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct on dataset.txt =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/1355 [00:00<?, ? examples/s]

Map:   0%|          | 0/72 [00:00<?, ? examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Loss: 2.2414
Validation Perplexity: 9.41

In [2]:
# ==================== FFT UNSUP TEST 3 ====================

run_unsupervised_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    corpus_path="dataset.txt",
    token=os.getenv("HF_TOKEN"),
    num_epoch=5,
    batch_size=1,
    grad_accum_steps=8,
    lr=5e-6,
    max_seq_length=512,
    chunk_size_sym=1500,
    overlap_sym=150,
    val_split=0.05,
    optim="adamw_torch_fused",
    test_status=False,
)

===== UNSUPERVISED FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct on dataset.txt =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/1355 [00:00<?, ? examples/s]

Map:   0%|          | 0/72 [00:00<?, ? examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Loss: 2.1898
Validation Perplexity: 8.93

In [2]:
# ==================== FFT UNSUP TEST 4 ====================

run_unsupervised_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    corpus_path="dataset.txt",
    token=os.getenv("HF_TOKEN"),
    num_epoch=3,
    batch_size=1,
    grad_accum_steps=12,
    lr=1e-5,
    max_seq_length=1024,
    chunk_size_sym=3000,
    overlap_sym=300,
    val_split=0.05,
    optim="adamw_torch_fused",
    test_status=False,
)

===== UNSUPERVISED FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct on dataset.txt =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/678 [00:00<?, ? examples/s]

Map:   0%|          | 0/36 [00:00<?, ? examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Loss: 2.0561
Validation Perplexity: 7.82

In [3]:
# ==================== FFT UNSUP TEST 5 ====================

run_unsupervised_full_finetune(
    model_name="meta-llama/Llama-3.1-8B-Instruct",
    corpus_path="dataset.txt",
    token=os.getenv("HF_TOKEN"),
    num_epoch=3,
    batch_size=1,
    grad_accum_steps=12,
    lr=5e-6,
    max_seq_length=1024,
    chunk_size_sym=3000,
    overlap_sym=300,
    val_split=0.05,
    optim="adamw_torch_fused",
    test_status=False,
)

===== UNSUPERVISED FULL FINETUNE: meta-llama/Llama-3.1-8B-Instruct on dataset.txt =====

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Map:   0%|          | 0/678 [00:00<?, ? examples/s]

Map:   0%|          | 0/36 [00:00<?, ? examples/s]

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

[transformers] There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Validation Loss: 2.1908
Validation Perplexity: 8.94